USE [master]
GO
/****** Object:  Database [TeamMgtSystem]    Script Date: 19-07-2019 07:36:56 AM ******/
CREATE DATABASE [TeamMgtSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TeamMgtSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TeamMgtSystem.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TeamMgtSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TeamMgtSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TeamMgtSystem] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TeamMgtSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TeamMgtSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TeamMgtSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TeamMgtSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TeamMgtSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TeamMgtSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TeamMgtSystem] SET  MULTI_USER 
GO
ALTER DATABASE [TeamMgtSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TeamMgtSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TeamMgtSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TeamMgtSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [TeamMgtSystem] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TeamMgtSystem]
GO
/****** Object:  Table [dbo].[Coach]    Script Date: 19-07-2019 07:36:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Coach](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CoachName] [varchar](50) NULL,
 CONSTRAINT [PK_Coach] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Login]    Script Date: 19-07-2019 07:36:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Login](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Player]    Script Date: 19-07-2019 07:36:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Player](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Position] [varchar](50) NULL,
	[Gender] [varchar](50) NULL,
	[TeamID] [int] NULL,
	[CoachName] [varchar](50) NULL,
 CONSTRAINT [PK_Player] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Team]    Script Date: 19-07-2019 07:36:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Team](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TeamName] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[State] [varchar](50) NULL,
	[CoachID] [int] NULL,
 CONSTRAINT [PK_Team] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[Coach] ON 

GO
INSERT [dbo].[Coach] ([ID], [CoachName]) VALUES (2, N'Nirmal Singh')
GO
SET IDENTITY_INSERT [dbo].[Coach] OFF
GO
ALTER TABLE [dbo].[Player]  WITH CHECK ADD  CONSTRAINT [FK_Player_Team] FOREIGN KEY([TeamID])
REFERENCES [dbo].[Team] ([ID])
GO
ALTER TABLE [dbo].[Player] CHECK CONSTRAINT [FK_Player_Team]
GO
ALTER TABLE [dbo].[Team]  WITH CHECK ADD  CONSTRAINT [FK_Team_Coach] FOREIGN KEY([CoachID])
REFERENCES [dbo].[Coach] ([ID])
GO
ALTER TABLE [dbo].[Team] CHECK CONSTRAINT [FK_Team_Coach]
GO
USE [master]
GO
ALTER DATABASE [TeamMgtSystem] SET  READ_WRITE 
GO
